camera_pub_node:
  ros__parameters:
    camera_source: "0"   # webcam id or video path !absolute path!

gt_test_node:
  ros__parameters:
    marker_size_mm: 10.0
    camera_matrix: [611.132, 324.398, 612.865, 230.317]   # fx, cx, fy, cy
    distortion_matrix: [-0.014771,   -0.1411372,  -0.00102157, -0.00217703,  0.17431914]
