camera_pub_node:
  ros__parameters:
    camera_source: "2"   # webcam id or video path !absolute path!

gt_test_node:
  ros__parameters:
    marker_size_mm: 151.0
    camera_matrix: [753.611, 338.179, 752.676, 241.622] # fx, cx, fy, cy
    distortion_matrix: [ 0.08098212, -0.21402227,  0.,          0.,          0.        ]
